//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Horizon.Core;
using UnityEngine;
using Horizon.Core.WeakSubscription;


namespace Horizon.Combat.Models
{
	public class Cell : ModelBase
	{
		public bool Passable;

		public float CellSize
		{
			get
			{
				return m_cellSizeSerilized;
			}
			set
			{
				SetPropertyFeild(ref m_cellSizeSerilized, value, () => CellSize);
			}
		}

		//private float derp;

		[SerializeField]
		private float m_cellSizeSerilized = 1;

		[SerializeField]
		private Grid m_gridSerilized;

		[SerializeField]
		private GridPoint m_gridPoint;


	}
}

