//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Horizon.Core.Editor
{
	public class CustomDrawer
	{
		public virtual object Draw(string label, object val){ return null; }
	}

	public class CustomDrawerAtribute : Attribute
	{
		public Type type;

		public CustomDrawerAtribute(Type type)
		{
			this.type = type;
		}
	}
}

