//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;


namespace Horizon.Core.Editor
{
	public class CustomDrawerAttribute : Attribute
	{
		public CustomDrawerAttribute(Type type, Func<string,object,object> draw)
		{
			drawFunctions[type] = draw;
		}

		static CustomDrawerAttribute()
		{
			drawFunctions = new Dictionary<Type, Func<string,object,object>>();
		}

		public static Dictionary<Type, Func<string,object,object>> drawFunctions; 
	}
}

