//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Horizon.Core.Editor;
using UnityEditor;
using UnityEngine;


namespace Horizon.Combat.Editor
{
	public class CustomDrawers
	{
		[CustomDrawerAtribute(typeof(GridPoint))]
		public class GridPointDrawer : CustomDrawer
		{
			public override object Draw (string label, object val)
			{
				GridPoint value = (GridPoint)val;

				EditorGUI.indentLevel++;
				GUILayout.BeginVertical();

				GUILayout.Label(label);

				GUILayout.BeginHorizontal();

				GUILayout.Label("X");
				int x = EditorGUILayout.IntField(value.x);
				
				GUILayout.Label("Y");
				int y = EditorGUILayout.IntField(value.y);

				GUILayout.EndHorizontal();

				GUILayout.EndVertical();
				EditorGUI.indentLevel--;
				
				return new GridPoint(x,y);
			}
		}
	}
}

