//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Horizon.Combat.GameObjects;
using Horizon.Core.Editor;


namespace Horizon.Combat.Editor
{
	public class GridSceneView : SceneView<Grid>
	{

	}
}

