//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Horizon.Combat.Models;
using Horizon.Core.Editor;
using Horizon.Core.Editor.Gizmos;
using UnityEngine;
using Horizon.Core.ExtensionMethods;
using Horizon.Core.WeakSubscription;


namespace Horizon.Combat.Editor
{
	public class CellSceneHighlight : SceneView<Cell>
	{
		protected override void Init ()
		{
			base.Init ();

			PassableColor = Color.cyan.SetAlpha(0.1f);
			ImpassableColor = Color.black.SetAlpha(0.4f);

			m_rectangleGizmo = new RectangleGizmo(model);

			m_rectangleGizmo.color = model.Passable ? PassableColor : ImpassableColor;
			model.WeakSubscribeToProperty(()=>model.Passable, (s,a) => {
				m_rectangleGizmo.color = model.Passable ? PassableColor : ImpassableColor;
			});
		}

		public override void Dispose ()
		{
			if(m_rectangleGizmo != null)
				m_rectangleGizmo.Dispose();
		}

		private RectangleGizmo m_rectangleGizmo;

		private Color PassableColor;
		private Color ImpassableColor;
	}
}

