//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Horizon.Combat.Models;
using Horizon.Core.Editor;
using Horizon.Core.Editor.Gizmos;
using UnityEngine;
using Horizon.Core.ExtensionMethods;
using Horizon.Core.WeakSubscription;


namespace Horizon.Combat.Editor
{
	//public class CellSelectedLabel : SceneView<Cell>
	//{
		//protected override void WhileSelected ()
		//{
			//base.WhileSelected ();
			//Debug.Log(gameObject.name);
		//}
	//}
}

