//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Horizon.Combat.Models;
using Horizon.Core.Editor;
using Horizon.Core.Editor.Gizmos;
using UnityEngine;
using Horizon.Core.ExtensionMethods;
using Horizon.Core.WeakSubscription;


namespace Horizon.Combat.Editor
{
	public class CellSceneHighlight : SceneView<Cell>
	{
		public int testPrefabConnection = 1;

		protected override void Init ()
		{
			base.Init ();
			m_rectangleGizmo = new RectangleGizmo(model);
			m_rectangleGizmo.color = Color.cyan.SetAlpha(0.4f);
			m_rectangleGizmo.Size = model.CellSize;
			model.WeakSubscribeToProperty(() => model.CellSize, (s,a) => m_rectangleGizmo.Size = model.CellSize);
		}

		public override void Dispose ()
		{
			if(m_rectangleGizmo != null)
				m_rectangleGizmo.Dispose();
		}

		private RectangleGizmo m_rectangleGizmo;
	}
}

