//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Horizon.Combat.Models;
using Horizon.Core.Editor;
using UnityEngine;
using UnityEditor;
using Horizon.Core.ExtensionMethods;
using Horizon.Core;


namespace Horizon.Combat.Editor
{
	//draw dotted grid lins in the sceneview
	public class GridSceneView : ViewBase<Grid>
	{
		public override void SceneViewUpdate ()
		{
			base.SceneViewUpdate ();

			Handles.color = Color.white.SetAlpha(0.25f);

			foreach(GridLine line in model.GridLines)
			{
				Handles.DrawDottedLine(line.start,line.end,4);
			}
		}
	}
}

