//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace Horizon.Core.ExtensionMethods
{
	public static class ColorExtensionMethods
	{
		public static Color SetAlpha(this Color self, float alpha)
		{
			return new Color(self.r,self.g,self.b,alpha);
		}
	}
}

