//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Horizon.Core;
using UnityEngine;


namespace Horizon.Combat.GameObjects
{
	public class Cell : HorizonGameObjectBase
	{
		public float CellSize
		{
			get
			{
				return m_cellSizeSerilized;
			}
			set
			{
				SetPropertyFeild(ref m_cellSizeSerilized, value, () => CellSize);
			}
		}

		[SerializeField]
		private float m_cellSizeSerilized = 1;
	}
}

