//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace Horizon.Core
{	
	public class ScriptableInit : ScriptableObject , ISerializationCallbackReceiver, IDisposable
	{
		bool initilized = false;

		public ScriptableInit()
		{
			Initilizer.CallOnInit(Init);
		}

		#region ISerializationCallbackReceiver implementation

		public void OnBeforeSerialize ()
		{
			if(!initilized) Init();
		}

		public void OnAfterDeserialize ()
		{
			if(!initilized) Init();
		}

		#endregion
		
		protected virtual void Init(){ initilized = true; }

		#region IDisposable implementation

		public virtual void Dispose (){}

		#endregion

		private void OnDestroy()
		{
			Dispose();
		}
	}

	public class InitBehavior : MonoBehaviour, ISerializationCallbackReceiver, IDisposable
	{
		bool constructed = false;

		public InitBehavior()
		{
			Initilizer.StartConstruction();
			Initilizer.CallOnInit(Init);
		}

		protected virtual void Init(){}

		#region ISerializationCallbackReceiver implementation
		public void OnBeforeSerialize ()
		{
			if(!constructed) 
			{
				Initilizer.EndConstruction();
				constructed = true;
			}
		}
		public void OnAfterDeserialize ()
		{
			if(!constructed) 
			{
				Initilizer.EndConstruction();
				constructed = true;
			}
		}
		#endregion

		#region IDisposable implementation

		public virtual void Dispose (){}

		#endregion

		private void OnDestroy()
		{
			Dispose();
		}

	}
}

