//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Horizon.Combat
{
	[Serializable]
	public struct GridPoint
	{
		public GridPoint(int x, int y)
		{
			this.x = x;
			this.y = y;
		}

		public int x;
		public int y;
	}
}

