//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace Horizon.Core.GL
{
	public class GLLine : GLObject
	{
		public Vector3 StartPoint;
		public Vector3 EndPoint;

		public override void Draw()
		{
			UnityEngine.GL.Begin( UnityEngine.GL.LINES );
			
			UnityEngine.GL.Vertex(StartPoint);
			UnityEngine.GL.Vertex(EndPoint);
			
			UnityEngine.GL.End();
		}
	}
}

