//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace Horizon.Core.GL
{
	public static class GLUtility
	{
		public static Material DefaultMaterial
		{
			get
			{
				if(m_defaultMaterial == null)
				{
					var shader = Shader.Find ("Hidden/Internal-Colored");
					var mat = new Material (shader);
					mat.hideFlags = HideFlags.HideAndDontSave;
					m_defaultMaterial = mat;
				}

				return m_defaultMaterial;
			}
		}

		private static Material m_defaultMaterial;
	}
}

